"""Run an LLM-based integration check against rendered markdown outputs."""

from __future__ import annotations

import argparse
import importlib
import json
import os
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

OUTPUT_DIR = Path("_out/md")
TEST_OUTPUT_DIR = Path("_out/tests")
RULES_FILE = Path("rules/integration_rules.yaml")
JUNIT_FILE = TEST_OUTPUT_DIR / "integration_test_report.junit.xml"
DEFAULT_MODEL = "openai/gpt-4o-mini"


@dataclass
class Rule:
    """Single integration rule loaded from YAML."""

    id: str
    description: str


def parse_rules_yaml(path: Path) -> list[Rule]:
    """Parse the constrained YAML schema used by integration rules."""
    if not path.exists():
        raise FileNotFoundError(f"Rules file not found: {path}")

    lines = path.read_text(encoding="utf-8").splitlines()
    rules: list[Rule] = []
    current_id: str | None = None
    description_parts: list[str] = []
    reading_description = False

    def flush_current() -> None:
        nonlocal current_id, description_parts, reading_description
        if current_id:
            description = " ".join(part.strip() for part in description_parts).strip()
            rules.append(Rule(id=current_id, description=description))
        current_id = None
        description_parts = []
        reading_description = False

    for raw_line in lines:
        line = raw_line.rstrip()
        stripped = line.strip()

        if not stripped or stripped.startswith("#"):
            continue

        if stripped.startswith("- id:"):
            flush_current()
            current_id = stripped.split(":", 1)[1].strip()
            continue

        if stripped.startswith("description:"):
            reading_description = True
            value = stripped.split(":", 1)[1].strip()
            if value and value != ">-":
                description_parts.append(value.strip('"'))
            continue

        if reading_description and line.startswith("      "):
            description_parts.append(stripped)

    flush_current()

    if not rules:
        raise ValueError("No rules parsed from YAML file")
    return rules


def read_markdown_outputs(output_dir: Path) -> dict[str, str]:
    """Read all markdown files generated by render workflow."""
    if not output_dir.exists():
        raise FileNotFoundError(
            f"Output directory not found: {output_dir}. Run render first."
        )

    markdown_files = sorted(output_dir.glob("*.md"))
    if not markdown_files:
        raise ValueError(f"No markdown files found under {output_dir}")

    return {f.name: f.read_text(encoding="utf-8") for f in markdown_files}


def build_messages(rules: list[Rule], markdown_files: dict[str, str]) -> list[dict[str, str]]:
    """Build system and user prompt messages for model evaluation."""
    rules_block = "\n".join(f"- {rule.id}: {rule.description}" for rule in rules)
    docs_block = "\n\n".join(
        f"### FILE: {name}\n```md\n{content}\n```" for name, content in markdown_files.items()
    )

    system_prompt = (
        "You are an integration test evaluator. "
        "Assess rules against provided markdown files. "
        "Return strict JSON only, with no markdown fences and no prose."
    )
    user_prompt = (
        "Evaluate these rules against all markdown files.\n"
        "Rules:\n"
        f"{rules_block}\n\n"
        "Output JSON schema exactly:\n"
        "{\n"
        '  "all_rules_passed": boolean,\n'
        '  "rules": [\n'
        "    {\n"
        '      "id": string,\n'
        '      "passed": boolean,\n'
        '      "failure_reason": string,\n'
        '      "findings": [\n'
        "        {\n"
        '          "file": string,\n'
        '          "snippet": string,\n'
        '          "reason": string\n'
        "        }\n"
        "      ]\n"
        "    }\n"
        "  ],\n"
        '  "summary": string\n'
        "}\n\n"
        "Files:\n"
        f"{docs_block}"
    )

    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def parse_model_json(content: str) -> dict[str, Any]:
    """Parse model response, tolerating accidental prose around JSON."""
    cleaned = content.strip()
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", cleaned)
        if not match:
            raise ValueError("Model response did not contain JSON object")
        return json.loads(match.group(0))


def normalize_result(result: dict[str, Any], rules: list[Rule]) -> dict[str, Any]:
    """Ensure result has stable keys and explicit failure reasons per rule."""
    incoming_rules = result.get("rules")
    by_id = {
        entry.get("id"): entry
        for entry in incoming_rules
        if isinstance(entry, dict) and isinstance(entry.get("id"), str)
    } if isinstance(incoming_rules, list) else {}

    normalized_rules: list[dict[str, Any]] = []
    all_passed = True

    for expected in rules:
        entry = by_id.get(expected.id, {})
        passed = bool(entry.get("passed", False))
        findings = entry.get("findings") if isinstance(entry.get("findings"), list) else []

        failure_reason = str(entry.get("failure_reason", "")).strip()
        if not passed and not failure_reason:
            finding_reasons = []
            for finding in findings if isinstance(findings, list) else []:
                if isinstance(finding, dict):
                    reason = str(finding.get("reason", "")).strip()
                    if reason:
                        finding_reasons.append(reason)
            failure_reason = finding_reasons[0] if finding_reasons else "Rule failed without a model-provided reason."

        normalized_rules.append(
            {
                "id": expected.id,
                "description": expected.description,
                "passed": passed,
                "failure_reason": failure_reason,
                "findings": findings,
            }
        )
        if not passed:
            all_passed = False

    summary = str(result.get("summary", "")).strip()
    if not summary:
        summary = "All rules passed." if all_passed else "One or more rules failed."

    return {
        "all_rules_passed": all_passed,
        "summary": summary,
        "rules": normalized_rules,
    }


def run_model_check(model: str, rules: list[Rule], markdown_files: dict[str, str]) -> dict[str, Any]:
    """Call OpenRouter model and return parsed JSON decision."""
    try:
        openrouter_module = importlib.import_module("openrouter")
    except ModuleNotFoundError as exc:
        raise ImportError(
            "Missing dependency: openrouter. Install with `pip install openrouter`."
        ) from exc

    open_router_cls = getattr(openrouter_module, "OpenRouter", None)
    if open_router_cls is None:
        raise ImportError("Installed openrouter package does not expose OpenRouter")

    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        raise EnvironmentError("OPENROUTER_API_KEY is required")

    messages = build_messages(rules, markdown_files)

    with open_router_cls(api_key=api_key) as client:
        response = client.chat.send(model=model, messages=messages)

    if not response.choices:
        raise ValueError("OpenRouter response did not contain choices")

    content = response.choices[0].message.content or ""
    if not content.strip():
        raise ValueError("OpenRouter returned empty content")

    return parse_model_json(content)


def write_junit_report(report_path: Path, model: str, result: dict[str, Any], dry_run: bool) -> None:
    """Write standardized JUnit XML output for CI/test tooling."""
    rules = result.get("rules", [])
    failures = sum(1 for rule in rules if not bool(rule.get("passed", False)))

    suite = ET.Element(
        "testsuite",
        name="render.integration_rules",
        tests=str(len(rules)),
        failures=str(failures),
        errors="0",
        skipped="0",
        timestamp=datetime.now(timezone.utc).isoformat(),
    )

    properties = ET.SubElement(suite, "properties")
    ET.SubElement(properties, "property", name="model", value=model)
    ET.SubElement(properties, "property", name="dry_run", value=str(dry_run).lower())
    ET.SubElement(properties, "property", name="summary", value=str(result.get("summary", "")))

    for rule in rules:
        rule_id = str(rule.get("id", "unknown_rule"))
        testcase = ET.SubElement(
            suite,
            "testcase",
            classname="render.integration_rules",
            name=rule_id,
        )

        passed = bool(rule.get("passed", False))
        if passed:
            continue

        failure_reason = str(rule.get("failure_reason", "Rule failed without a reason."))
        findings = rule.get("findings", [])
        finding_lines: list[str] = []
        if isinstance(findings, list):
            for finding in findings:
                if not isinstance(finding, dict):
                    continue
                file_name = str(finding.get("file", "unknown"))
                snippet = str(finding.get("snippet", "")).strip()
                reason = str(finding.get("reason", "")).strip()
                finding_lines.append(
                    f"- file={file_name}; reason={reason}; snippet={snippet}"
                )

        details = "\n".join(finding_lines) if finding_lines else "No findings provided by model."
        ET.SubElement(
            testcase,
            "failure",
            message=failure_reason,
            type="RuleViolation",
        ).text = details

    report_path.parent.mkdir(parents=True, exist_ok=True)
    tree = ET.ElementTree(suite)
    ET.indent(tree, space="  ")
    tree.write(report_path, encoding="utf-8", xml_declaration=True)


def run_dry_run(rules: list[Rule]) -> dict[str, Any]:
    """Create a deterministic local result without calling OpenRouter."""
    return {
        "all_rules_passed": True,
        "rules": [
            {
                "id": rule.id,
                "passed": True,
                "failure_reason": "",
                "findings": [],
            }
            for rule in rules
        ],
        "summary": "Dry run mode enabled; model call skipped.",
    }


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=DEFAULT_MODEL, help="OpenRouter model id")
    parser.add_argument(
        "--rules-file",
        default=str(RULES_FILE),
        help="Path to integration rules YAML file",
    )
    parser.add_argument(
        "--output-dir",
        default=str(OUTPUT_DIR),
        help="Directory containing rendered markdown outputs",
    )
    parser.add_argument(
        "--junit-file",
        default=str(JUNIT_FILE),
        help="Path to JUnit XML report file",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Skip OpenRouter call and write deterministic passing output",
    )
    return parser.parse_args()


def main() -> None:
    """Run integration rule evaluation and fail process if rules fail."""
    args = parse_args()
    rules = parse_rules_yaml(Path(args.rules_file))
    markdown_files = read_markdown_outputs(Path(args.output_dir))

    raw_result = run_dry_run(rules) if args.dry_run else run_model_check(args.model, rules, markdown_files)
    result = normalize_result(raw_result, rules)
    write_junit_report(Path(args.junit_file), args.model, result, args.dry_run)

    if result.get("all_rules_passed"):
        print("Integration checks passed. " f"JUnit report: {args.junit_file}")
        return

    print(
        "Integration checks failed. "
        f"JUnit report: {args.junit_file}",
        file=sys.stderr,
    )
    sys.exit(1)


if __name__ == "__main__":
    main()

